outFile = open("../x54x_bootloader.h","w") 
bootloaderFile = open("bootloader.bin", "rb")

outFile.write("// This file is generated by bootloader_update_x54x_bin\\bootloaderToHeader.py using bootloader_update_x54x_bin\\bootloader.bin as an input\n\n")

outFile.write("uint8_t bootloaderData[] = {")

data = bootloaderFile.read()

written = 0

line = "\n"

for i in range(0, len(data)):
    line += str("0x{:02x}".format(data[i])) + ", "

    if (i + 1) % 8 == 0 or i == len(data) - 1:
        line += "\n"
        outFile.write(line)
        line = ""

outFile.write("};")

outFile.close()
bootloaderFile.close()
