Metadata meta
int32 id
string cmd
string file_name
string[] update_queue
---
Metadata meta
int32 id
string cmd
int32 err
string[] videos
string[] queue
string msg
string status 
string video_playing
bool is_video_on 